using UnityEngine;

public class PlayerRespawn : MonoBehaviour
{
    private Vector3 lastCheckpoint;
    private CharacterController controller;

    void Start()
    {
        controller = GetComponent<CharacterController>();
        lastCheckpoint = transform.position; // posici√≥n inicial
    }

    public void UpdateCheckpoint(Vector3 newCheckpoint)
    {
        lastCheckpoint = newCheckpoint;
        Debug.Log("Nuevo checkpoint guardado en: " + newCheckpoint);
    }

    public void Respawn()
    {
        controller.enabled = false;
        transform.position = lastCheckpoint;
        controller.enabled = true;
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("DeathZone"))
        {
            GameManager.Instance.AddFall();

            ControllerScene2 controllerScene = FindObjectOfType<ControllerScene2>();
            if (controllerScene != null)
                controllerScene.ActualizarTextoCaidas();

            Respawn();
        }
    }
}

